# Homework Numpy

In [2]:
import numpy as np

## Excercise 1

In [18]:
def make_reversed_array(n):
    list_ = [i for i in range(0,n)]
    list_.reverse()
    return np.array(list_)
    
make_reversed_array(10)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

## Excercise 2

In [19]:
a = np.diagflat(make_reversed_array(10))

print(a)
print(np.trace(a))

[[9 0 0 0 0 0 0 0 0 0]
 [0 8 0 0 0 0 0 0 0 0]
 [0 0 7 0 0 0 0 0 0 0]
 [0 0 0 6 0 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0 0]
 [0 0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]]
45


## Excercise 3

Решите систему уравнений:
$$
\begin{cases} 
    4x + 2y + z = 4 \\ 
    1x + 3y = 12 \\ 
    5y + 4z = -3 
\end{cases} 
$$

In [49]:
coefs = [[4, 2, 1],[1, 3, 0],[0, 5, 4],[4, 12, -3]]

def solve_lin_sys(coef_list):
    """
    Функция решает заданную СЛАУ без проверки на наличие решения (!) матричным методом.
    coef_list представляет собой список из списков коэфффициентов при неизвестных, а последний список - обязательно свободные члены.
    """
    
    left_matrix = np.array(coef_list[0:len(coef_list) - 1])
    right_matrix = np.array(coef_list[-1])
    
    return np.linalg.solve(left_matrix, right_matrix)
    
print('x={}\ny={}\nz={}'.format(round(solve_lin_sys(coefs)[0],2), 
                                round(solve_lin_sys(coefs)[1],2), 
                                round(solve_lin_sys(coefs)[2],2)))

x=0.47
y=3.84
z=-5.56


## Excercise 4

In [20]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

In [21]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

def max_similar_user(new_user, stats=users_stats):
    """Функция возвращает номер пользователя максимально похожего на нового по методу косинусной близости"""
    
    cosine = lambda a, b: np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))
    similarity_dict = {i+1: cosine(new_user, line) for i, line in enumerate(users_stats)} # словарь вида {id: cos}
    for user_id, cos in similarity_dict.items():
        if cos == max(similarity_dict.values()):
            return user_id

max_similar_user(next_user_stats)

2